CREATE TABLE UpdateTickets (
	ID INT  NOT NULL AUTO_INCREMENT,
    
    CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_USER VARCHAR(64) CHARSET utf8 NOT NULL,
    
    URI VARCHAR(256) CHARSET utf8 NOT NULL,
    PROPERTY VARCHAR(64) CHARSET utf8 NOT NULL,
    IDX INT,
    OLD_VALUE TEXT CHARSET utf8 NOT NULL,
    NEW_VALUE TEXT CHARSET utf8 NOT NULL,
    LANGUAGE VARCHAR(64) CHARSET utf8 NULL,

    STATUS VARCHAR(64) CHARSET utf8 NOT NULL,
    ACTION_USER VARCHAR(64) CHARSET utf8 NULL,
    ACTION_DATE TIMESTAMP NULL,
    COMMENT TEXT CHARSET utf8 NULL,
    
    primary key (ID)
);